
library(shiny)
library(shinythemes)
library(VGAM)
library(ggplot2)

# model <- readRDS("C:/Users/jared/OneDrive/Desktop/Shiny/Shiny_Projects/magic_dependency/contratio_model.RDS")
model <- readRDS("contratio_model.RDS")

ui <- fluidPage(
  theme = shinytheme("superhero"),
  navbarPage(
    "Predicting Magical Dependencies",
    
    tabPanel("Introduction",
             fluidRow(
               column(12,
                      HTML('
            <div style="padding: 15px; background-color: transparent; border-radius: 8px; margin-bottom: 20px; color: #ccc;">
              <h3>Project Description</h3>
              <p>
                This Shiny app allows users to predict the Magical Dependency of their 5\'th Edition Dungeons and Dragons playable characters.
                Rather than predicting the exact playable class, each original 5\'th Edition Player\'s Handbook class is grouped into four magical dependency subcategories.
                This allows for easier interpretation and comparison between groups and a less complicated model.
              </p>
              <p>
                The user inputs required include all six attribute scores (strength, dexterity, constitution, inteligence, wisdom, charisma), player level, current hit points, and also fields for refined race and refined background.
                Refined race and background are subcategories of the original races and backgrounds from the Player\'s Handbook and are grouped for faster computation time and more interpretability of covariate effects.
              </p>
              <p>
                To understand how classes are defined into multiple Magical Dependency categroies, the Class Transformation table is provided below,
                as well as the Background and Race transformation tables. 
              </p>
              <p>
              To determine an appropriate transformation from class to magical dependency, each class was ordered from least magic dependent to most magic dependent.
                Due to the subjective nature of this ordering, two other orderings were also considered, one generated by OpenAI, and one from a local dungeon master.
                Each ranking differed in exact order, however, four groupings were consistent across all three rankings, leading to our four magical dependency subcategories.
              </p>
              <p>
              Future work is being done to predict the exact class of each 5\'th Edition Playable Character.
              </p>
              
              <table style="width:100%; border-collapse: collapse; color: #ccc;  margin-bottom: 30px;">
                <caption style="caption-side: top; font-weight: bold; font-size: 1.3em; margin-bottom: 10px; color: #ccc;">
                  Class Transformation Table
                </caption>
                <thead>
                  <tr style="background-color: #444;">
                    <th style="border: 1px solid #666; padding: 8px;">Self Ranking</th>
                    <th style="border: 1px solid #666; padding: 8px;">OpenAI Ranking</th>
                    <th style="border: 1px solid #666; padding: 8px;">Local DM Ranking</th>
                    <th style="border: 1px solid #666; padding: 8px;">Magical Dependency</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Rogue</td>
                    <td style="border: 1px solid #666; padding: 8px;">Fighter</td>
                    <td style="border: 1px solid #666; padding: 8px;">Barbarian</td>
                    <td style="border: 1px solid #666; padding: 8px;">Non-Magic</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Barbarian</td>
                    <td style="border: 1px solid #666; padding: 8px;">Barbarian</td>
                    <td style="border: 1px solid #666; padding: 8px;">Fighter</td>
                    <td style="border: 1px solid #666; padding: 8px;">Non-Magic</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Fighter</td>
                    <td style="border: 1px solid #666; padding: 8px;">Rogue</td>
                    <td style="border: 1px solid #666; padding: 8px;">Rogue</td>
                    <td style="border: 1px solid #666; padding: 8px;">Non-Magic</td>
                  </tr>
                  <tr style="font-weight: bold; background-color: #703126;">
                    <td style="border: 1px solid #666; padding: 8px;">Monk</td>
                    <td style="border: 1px solid #666; padding: 8px;">Monk</td>
                    <td style="border: 1px solid #666; padding: 8px;">Monk</td>
                    <td style="border: 1px solid #666; padding: 8px;">Semi-Magic</td>
                  </tr>
                  <tr style="font-weight: bold; background-color: #703126;">
                    <td style="border: 1px solid #666; padding: 8px;">Ranger</td>
                    <td style="border: 1px solid #666; padding: 8px;">Ranger</td>
                    <td style="border: 1px solid #666; padding: 8px;">Ranger</td>
                    <td style="border: 1px solid #666; padding: 8px;">Semi-Magic</td>
                  </tr>
                  <tr style="font-weight: bold; background-color: #703126;">
                    <td style="border: 1px solid #666; padding: 8px;">Paladin</td>
                    <td style="border: 1px solid #666; padding: 8px;">Paladin</td>
                    <td style="border: 1px solid #666; padding: 8px;">Paladin</td>
                    <td style="border: 1px solid #666; padding: 8px;">Semi-Magic</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Bard</td>
                    <td style="border: 1px solid #666; padding: 8px;">Bard</td>
                    <td style="border: 1px solid #666; padding: 8px;">Warlock</td>
                    <td style="border: 1px solid #666; padding: 8px;">Mostly-Magic</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Cleric</td>
                    <td style="border: 1px solid #666; padding: 8px;">Warlock</td>
                    <td style="border: 1px solid #666; padding: 8px;">Bard</td>
                    <td style="border: 1px solid #666; padding: 8px;">Mostly-Magic</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Druid</td>
                    <td style="border: 1px solid #666; padding: 8px;">Cleric</td>
                    <td style="border: 1px solid #666; padding: 8px;">Druid</td>
                    <td style="border: 1px solid #666; padding: 8px;">Mostly-Magic</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Warlock</td>
                    <td style="border: 1px solid #666; padding: 8px;">Druid</td>
                    <td style="border: 1px solid #666; padding: 8px;">Cleric</td>
                    <td style="border: 1px solid #666; padding: 8px;">Mostly-Magic</td>
                  </tr>
                  <tr style="font-weight: bold; background-color: #703126;">
                    <td style="border: 1px solid #666; padding: 8px;">Sorcerer</td>
                    <td style="border: 1px solid #666; padding: 8px;">Sorcerer</td>
                    <td style="border: 1px solid #666; padding: 8px;">Sorcerer</td>
                    <td style="border: 1px solid #666; padding: 8px;">Highly-Magic</td>
                  </tr>
                  <tr style="font-weight: bold; background-color: #703126;">
                    <td style="border: 1px solid #666; padding: 8px;">Wizard</td>
                    <td style="border: 1px solid #666; padding: 8px;">Wizard</td>
                    <td style="border: 1px solid #666; padding: 8px;">Wizard</td>
                    <td style="border: 1px solid #666; padding: 8px;">Highly-Magic</td>
                  </tr>
                </tbody>
              </table>
              
              <table style="width:100%; border-collapse: collapse; color: #ccc; margin-bottom: 30px;">
                <caption style="caption-side: top; font-weight: bold; font-size: 1.3em; margin-bottom: 10px; color: #ccc;">
                  Background Transformation Table
                </caption>
                <thead>
                  <tr style="background-color: #444;">
                    <th style="border: 1px solid #666; padding: 8px;">Background</th>
                    <th style="border: 1px solid #666; padding: 8px;">Refined Background</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Criminal, Charlatan</td>
                    <td style="border: 1px solid #666; padding: 8px;">Shady</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Sailor, Guild Artisan, Entertainer, Soldier</td>
                    <td style="border: 1px solid #666; padding: 8px;">Industrial</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Hermit, Urchin, Outlander</td>
                    <td style="border: 1px solid #666; padding: 8px;">Loner</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Noble, Folk-Hero</td>
                    <td style="border: 1px solid #666; padding: 8px;">Famous</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Sage, Acolyte</td>
                    <td style="border: 1px solid #666; padding: 8px;">Magical</td>
                  </tr>
                </tbody>
              </table>
              
              <table style="width:100%; border-collapse: collapse; color: #ccc; margin-bottom: 30px;">
                <caption style="caption-side: top; font-weight: bold; font-size: 1.3em; margin-bottom: 10px; color: #ccc;">
                  Race Transformation Table
                </caption>
                <thead>
                  <tr style="background-color: #444;">
                    <th style="border: 1px solid #666; padding: 8px;">Race</th>
                    <th style="border: 1px solid #666; padding: 8px;">Refined Race</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Human</td>
                    <td style="border: 1px solid #666; padding: 8px;">Human</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Elf</td>
                    <td style="border: 1px solid #666; padding: 8px;">Elf</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Tiefling, Dragonborn</td>
                    <td style="border: 1px solid #666; padding: 8px;">Monster</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Gnome, Halfling, Dwarf</td>
                    <td style="border: 1px solid #666; padding: 8px;">Short</td>
                  </tr>
                  <tr>
                    <td style="border: 1px solid #666; padding: 8px;">Half-Orc, Half-Elf</td>
                    <td style="border: 1px solid #666; padding: 8px;">Hybrid</td>
                  </tr>
                </tbody>
              </table>
              
            </div>
          ')
        )
      )
    ),
    
    tabPanel("Prediction",
             fluidRow(
               column(6,  # Left half: input grid
                      fluidRow(
                        column(6, numericInput("hp", label = "HP", value = NA)),
                        column(6, numericInput("lev", label = "Level:", value = NA))
                      ),
                      fluidRow(
                        column(6, numericInput("str", label = "Strength", value = NA)),
                        column(6, numericInput("dex", label = "Dexterity", value = NA))
                      ),
                      fluidRow(
                        column(6, numericInput("con", label = "Constitution", value = NA)),
                        column(6, numericInput("intel", label = "Intelligence", value = NA))
                      ),
                      fluidRow(
                        column(6, numericInput("wis", label = "Wisdom", value = NA)),
                        column(6, numericInput("cha", label = "Charisma", value = NA))
                      ),
                      fluidRow(
                        column(6, selectInput("background", label = "Refined Background", 
                                              choices = c("Shady", "Industrial", "Loner", "Famous", "Magical"),
                                              selected = character(0))),
                        column(6, selectInput("race", label = "Refined Race", 
                                              choices = c("Human", "Elf", "Monster", "Short", "Hybrid"),
                                              selected = character(0)))
                      )
               ),
               column(6,  # Right half: prediction panel
                      tags$div(style = "margin-top: 25px;"),  # Spacer
                      actionButton("submit", "Predict Dependency"),
                      actionButton("reset", "Reset Inputs"),
                      h4("Predicted Magical Dependency:"),
                      verbatimTextOutput("prediction")
               )
             )
    ),
    
    tabPanel("Probabilities",
             fluidRow(
               column(6,  
                      fluidRow( ## HP and Level
                        column(6, sliderInput("hp_prob", label = ("HP"), min = 0, max = 300, value = 150)),
                        column(6, sliderInput("lev_prob", label = ("Level"), min = 0, max = 20, value = 10))
                      ),
                      fluidRow( ## Strength and Dex
                        column(6, sliderInput("str_prob", label = ("Strength"), min = 0, max = 20, value = 10)),
                        column(6, sliderInput("dex_prob", label = ("Dexterity"), min = 0, max = 20, value = 10))
                      ),
                      fluidRow( ## Strength and Dex
                        column(6, sliderInput("con_prob", label = ("Constitution"), min = 0, max = 20, value = 10)),
                        column(6, sliderInput("intel_prob", label = ("Intelligence"), min = 0, max = 20, value = 10))
                      ),
                      fluidRow( ## Strength and Dex
                        column(6, sliderInput("wis_prob", label = ("Wisdom"), min = 0, max = 20, value = 10)),
                        column(6, sliderInput("cha_prob", label = ("Charisma"), min = 0, max = 20, value = 10))
                      ),
                      fluidRow(
                        column(6, selectInput("background_prob", label = "Refined Background", 
                                              choices = c("Shady", "Industrial", "Loner", "Famous", "Magical"),
                                              selected = character(0))),
                        column(6, selectInput("race_prob", label = "Refined Race", 
                                              choices = c("Human", "Elf", "Monster", "Short", "Hybrid"),
                                              selected = character(0)))
                      )
               ),
               column(6,
                      plotOutput("prob_plot")
        )
      )
    )
  )
)


server <- function(input, output, session) {
  
  # Store prediction result
  prediction_value <- reactiveVal("")
  
  # Reactive expression for input data
  input_data <- reactive({
    data.frame(
      level = as.numeric(input$lev),
      hp = as.numeric(input$hp),
      strength = as.numeric(input$str),
      dex = as.numeric(input$dex),
      const = as.numeric(input$con),
      intelligence = as.numeric(input$intel),
      wisdom = as.numeric(input$wis),
      charisma = as.numeric(input$cha),
      refined_background = input$background,
      refined_race = input$race,
      stringsAsFactors = FALSE
    )
  })
  
  # Prediction on submit
  observeEvent(input$submit, {
    df <- input_data()
    probs <- predict(model, newdata = df, type = "response")
    predicts <- apply(probs, 1, which.max)
    
    prediction_label <- ifelse(predicts == 1, "Non-Magic", 
                               ifelse(predicts == 2, "Semi-Magic",
                                      ifelse(predicts == 3, "Mostly-Magic", "Highly-Magic")))
    
    prediction_classes <- ifelse(predicts == 1, "Rogue, Barbarian, or Fighter", 
                                 ifelse(predicts == 2, "Monk, Ranger, or Paladin",
                                        ifelse(predicts == 3, "Bard, Cleric, Druid, or Warlock", "Sorcerer or Wizard")))
    
    prediction_value(paste0(prediction_label, ": ", prediction_classes))
    
    # Sync values to third tab sliders after submit
    updateSliderInput(session, "hp_prob", value = input$hp)
    updateSliderInput(session, "lev_prob", value = input$lev)
    updateSliderInput(session, "str_prob", value = input$str)
    updateSliderInput(session, "dex_prob", value = input$dex)
    updateSliderInput(session, "con_prob", value = input$con)
    updateSliderInput(session, "intel_prob", value = input$intel)
    updateSliderInput(session, "wis_prob", value = input$wis)
    updateSliderInput(session, "cha_prob", value = input$cha)
    updateSelectInput(session, "background_prob", selected = input$background)
    updateSelectInput(session, "race_prob", selected = input$race)
    
  })
  
  # Output
  output$prediction <- renderText({
    prediction_value()
  })
  
  # Reset inputs and clear prediction
  observeEvent(input$reset, {
    updateNumericInput(session, "hp", value = NA)
    updateNumericInput(session, "lev", value = NA)
    updateNumericInput(session, "str", value = NA)
    updateNumericInput(session, "dex", value = NA)
    updateNumericInput(session, "con", value = NA)
    updateNumericInput(session, "intel", value = NA)
    updateNumericInput(session, "wis", value = NA)
    updateNumericInput(session, "cha", value = NA)
    updateSelectInput(session, "background", selected = character(0))  
    updateSelectInput(session, "race", selected = character(0))
    
    # Clear prediction
    prediction_value("")
    
    updateSliderInput(session, "hp_prob", value = 150)
    updateSliderInput(session, "lev_prob", value = 10)
    updateSliderInput(session, "str_prob", value = 10)
    updateSliderInput(session, "dex_prob", value = 10)
    updateSliderInput(session, "con_prob", value = 10)
    updateSliderInput(session, "intel_prob", value = 10)
    updateSliderInput(session, "wis_prob", value = 10)
    updateSliderInput(session, "cha_prob", value = 10)
    updateSelectInput(session, "background_prob", selected = character(0))
    updateSelectInput(session, "race_prob", selected = character(0))
  })
  
  ## make the plot ## 
  
  prob_data <- reactive({
    df <- data.frame(
      level = input$lev_prob,
      hp = input$hp_prob,
      strength = input$str_prob,
      dex = input$dex_prob,
      const = input$con_prob,
      intelligence = input$intel_prob,
      wisdom = input$wis_prob,
      charisma = input$cha_prob,
      refined_background = input$background_prob,
      refined_race = input$race_prob,
      stringsAsFactors = FALSE
    )
    
    probs <- predict(model, newdata = df, type = "response")
    
    prob_df <- data.frame(
      Dependency = c("Non-Magic", "Semi-Magic", "Mostly-Magic", "Highly-Magic"),
      Probability = probs[1,]
    )
    
    # Ensure correct ordering
    prob_df$Dependency <- factor(prob_df$Dependency, 
                                 levels = c("Non-Magic", "Semi-Magic", "Mostly-Magic", "Highly-Magic"))
    
    prob_df
  })
  
  output$prob_plot <- renderPlot({
    ggplot(data = prob_data(), aes(x = Dependency, y = Probability)) +
      geom_col(fill = "#56B4E9") +
      ylim(0, 1) +
      theme_bw() +
      labs(title = "Predicted Magical Dependency Probabilities",
           x = "Dependency",
           y = "Probability")
  })
  
}



shinyApp(ui = ui, server = server)
